[tools]
aws-cli = "latest"
go = "1.24"
node = "22"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:@google/gemini-cli" = "latest"
"pipx:aws-mfa" = "latest"
ruby = "3.4.7"
rust = "latest"
uv = "latest"
yarn = "4"

[settings]
trusted_config_paths = [
  "~/dotfiles"
]
idiomatic_version_file_enable_tools = [
	"ruby",
	"node",
	"go"
]

